problem:
  instance:
    C: 256
    Hdilation: 1
    Hstride: 2
    M: 512
    N: 1
    P: 7
    Q: 7
    R: 3
    S: 3
    Wdilation: 1
    Wstride: 2
  shape:
    coefficients:
    - default: 1
      name: Wstride
    - default: 1
      name: Hstride
    - default: 1
      name: Wdilation
    - default: 1
      name: Hdilation
    data_spaces:
    - name: Weights
      projection:
      - - - C
      - - - M
      - - - R
      - - - S
    - name: Inputs
      projection:
      - - - N
      - - - C
      - - - R
          - Hdilation
        - - P
          - Hstride
      - - - S
          - Wdilation
        - - Q
          - Wstride
    - name: Outputs
      projection:
      - - - N
      - - - M
      - - - P
      - - - Q
      read_write: true
    dimensions:
    - C
    - M
    - R
    - S
    - N
    - P
    - Q
    name: CNN_Layer
  version: 0.4
