mapper:
<<<<<<< HEAD
  version: 0.4
  optimization_metrics: [ delay, energy ]
  live_status: False
  num_threads: 8
  # [Change] 增加超时阈值，给它更多尝试机会
  timeout: 50000 
  victory_condition: 500
  algorithm: random_pruned
  max_permutations_per_if_visit: 16
=======
  optimization-metrics: [ delay, energy ]
  live-status: false
  num-threads: 8
  timeout: 1000
  victory-condition: 0
  algorithm: random-pruned

mapspace:
  constraints:
    # [Constraint 1] SRAM_Buffer (原 GlobalBuffer)
    # 强制利用 PE 阵列的空间并行性
    - target: SRAM_Buffer  # <--- 必须与 arch.yaml 中的 name 一致
      type: spatial
      permutation: CM      # 优先展开 Channel 和 Map 维度
      
    # [Constraint 2] RegFile
    # 强制 L0 寄存器做极致的数据复用 (Weight Stationary 风格)
    - target: RegFile      # <--- 必须与 arch.yaml 中的 name 一致
      type: temporal
      factors: [ R=1, S=1 ]
>>>>>>> d2ec8543f2de6810717e0b3d892adc03f09692e8
