mapper:
  version: 0.4
  optimization_metrics: [ delay, energy ]
  live_status: False
  num_threads: 8
  # [Change] 增加超时阈值，给它更多尝试机会
  timeout: 50000 
  victory_condition: 500
  algorithm: random_pruned
  max_permutations_per_if_visit: 16
