mapper:
  version: 0.4
  optimization_metrics: [ delay, energy ]
  live_status: false
  num_threads: 8
  timeout: 10000
  victory_condition: 100
  algorithm: hybrid
  diagnostics: false 

mapspace:
  template: uber

constraints:
  version: 0.4
  targets:
    # [FIX] 允许 PIM_Node 进行空间切分 (解决 Nodes > 1 的问题)
    - target: PIM_Node
      type: spatial

    # [Core] 强制使用 Node_SRAM (解决 Bypass 问题)
    - target: Node_SRAM
      type: dataspace
      keep: [Inputs, Outputs, Weights]
      bypass: []
    
    # Baseline: 自由探索 PE 阵列
    - target: PE_Array
      type: spatial
