mapper:
  version: 0.4
  optimization-metrics: [ delay, energy ]
  live-status: false
  num-threads: 8
  timeout: 15000
  victory-condition: 500
  algorithm: random-pruned
  max_permutations_per_if_visit: 16
