mapper:
  version: 0.4
  optimization_metrics: [ delay, energy ]
  live_status: false
  num_threads: 8
  algorithm: hybrid
  timeout: 10000
  victory_condition: 100
  
mapspace:
  version: 0.4
  template: uber
